#!/bin/bash

if test $(whoami) != root
then
	exec sudo $0 $@
fi

iptables -t nat -N REDSOCKS 2>/dev/null
iptables -t nat -F REDSOCKS
iptables -t nat -A REDSOCKS -d 127.0.0.1 -j RETURN
iptables -t nat -A REDSOCKS -d 10.0.0.0/8 -j RETURN
iptables -t nat -A REDSOCKS -p tcp -j REDIRECT --to-ports 12345

if ! iptables -t nat -L OUTPUT -n | grep REDSOCKS >/dev/null
then
	iptables -t nat -A OUTPUT -p tcp -j REDSOCKS
fi

service redsocks start
